options symbolgen mprint mlogic;
filename rwiOut ".";
ods html close;
ods html path=rwiOut file="Discovery.html" dom;
data _null_;
call symput(dt_atual, today());
run;
%put &dt_atual.;
%include "/tmp/discovery_ms/ProgramaSAS/tab_infoServidor.sas";
%include "/tmp/discovery_ms/ProgramaSAS/tab_infoCPU.sas";
%include "/tmp/discovery_ms/ProgramaSAS/tab_infoMEM.sas";
%include "/tmp/discovery_ms/ProgramaSAS/tab_infoRede.sas";
%include "/tmp/discovery_ms/ProgramaSAS/tab_infoDisco.sas";
%include "/tmp/discovery_ms/ProgramaSAS/sasinstallreport.sas";
ods html close;
ods html;
