data infoRede;
infile datalines delimiter='#' missover dsd;
length descricao $100 informacoes $255.;
input descricao $ informacoes $;
datalines;
DNS#   Generated by NetworkManager
DNS# search exnet.sas.com demo.sas.com
DNS# nameserver 149.173.5.54
DNS# nameserver 149.173.5.55
Placa de Rede# eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
Placa de Rede#         inet 10.96.6.76  netmask 255.255.0.0  broadcast 10.96.255.255
Placa de Rede# lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
Placa de Rede#         inet 127.0.0.1  netmask 255.0.0.0
Placa de Rede# virbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
Placa de Rede#         inet 192.168.122.1  netmask 255.255.255.0  broadcast 192.168.122.255
Status do Firewall#    Active: inactive (dead)
;
run;
proc print data=infoRede noobs;
title "Informacoes da Rede - SASSERVER.DEMO.SAS.COM";
run;
